package org.ops4j.pax.runner.idea.editor;/*
 * Copyright 2006 Niclas Hedhman.
 *
 * Licensed  under the  Apache License,  Version 2.0  (the "License");
 * you may not use  this file  except in  compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed  under the  License is distributed on an "AS IS" BASIS,
 * WITHOUT  WARRANTIES OR CONDITIONS  OF ANY KIND, either  express  or
 * implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JPanel;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.GridConstraints;
import java.awt.Insets;
import java.awt.Dimension;

public class RemoveRepositoryForm
{
    private JPanel m_mainPanel;
    private JButton m_remove;
    private JButton m_cancel;
    private JList m_repositories;

    public JPanel getMainPanel()
    {
        return m_mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     */
    private void $$$setupUI$$$()
    {
        m_mainPanel = new JPanel();
        m_mainPanel.setLayout( new GridLayoutManager( 2, 1, new Insets( 0, 0, 0, 0 ), -1, -1 ) );
        final JPanel panel1 = new JPanel();
        panel1.setLayout( new GridLayoutManager( 1, 5, new Insets( 0, 0, 0, 0 ), -1, -1 ) );
        m_mainPanel.add( panel1, new GridConstraints( 1, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                                                      GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                 | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                 GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                                 | GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                                 null, null, null, 0, false
        )
        );
        m_remove = new JButton();
        m_remove.setText( "Remove Selected" );
        panel1.add( m_remove, new GridConstraints( 0, 1, 1, 1, GridConstraints.ANCHOR_CENTER,
                                                   GridConstraints.FILL_HORIZONTAL, GridConstraints
            .SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                                          null, 0, false
        )
        );
        m_cancel = new JButton();
        m_cancel.setText( "Cancel" );
        panel1.add( m_cancel, new GridConstraints( 0, 3, 1, 1, GridConstraints.ANCHOR_CENTER,
                                                   GridConstraints.FILL_HORIZONTAL, GridConstraints
            .SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null,
                                                                          null, 0, false
        )
        );
        m_repositories = new JList();
        m_mainPanel.add( m_repositories, new GridConstraints( 0, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                                                              GridConstraints.FILL_BOTH,
                                                              GridConstraints.SIZEPOLICY_CAN_GROW,
                                                              GridConstraints.SIZEPOLICY_WANT_GROW, null,
                                                              new Dimension( 150, 50 ), null, 0, false
        )
        );
    }

    public javax.swing.JComponent $$$getRootComponent$$$()
    {
        return m_mainPanel;
    }
}
