/*
 * Copyright 2006 Niclas Hedhman.
 *
 * Licensed  under the  Apache License,  Version 2.0  (the "License");
 * you may not use  this file  except in  compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed  under the  License is distributed on an "AS IS" BASIS,
 * WITHOUT  WARRANTIES OR CONDITIONS  OF ANY KIND, either  express  or
 * implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ops4j.pixea.bundles.forms;

import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.DefaultListModel;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.GridConstraints;
import java.awt.Insets;
import java.util.ResourceBundle;
import org.ops4j.pixea.bundles.editor.DataBeanImport;

public class OsgiModuleImportForm
{

    private JList m_importList;
    private JPanel m_mainPanel;
    private DefaultListModel m_dataModel;

    private void createUIComponents()
    {
        m_dataModel = new DefaultListModel();
        m_importList = new JList( m_dataModel );
    }

    public void setData( DataBeanImport data )
    {
    }

    public void getData( DataBeanImport data )
    {
    }

    public boolean isModified( DataBeanImport data )
    {
        return false;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection HardCodedStringLiteral
     */
    private void $$$setupUI$$$()
    {
        createUIComponents();
        m_mainPanel = new JPanel();
        m_mainPanel.setLayout( new GridLayoutManager( 2, 1, new Insets( 0, 0, 0, 0 ), -1, -1 ) );
        m_mainPanel.setBorder( BorderFactory.createTitledBorder( BorderFactory.createEtchedBorder(),
                                                                 ResourceBundle.getBundle(
                                                                     "org/ops4j/pixea/runner/idea/OsgiResourceBundle"
                                                                 ).getString( "settings.import.title" )
        )
        );
        final JLabel label1 = new JLabel();
        this.$$$loadLabelText$$$( label1,
                                  ResourceBundle.getBundle( "org/ops4j/pixea/runner/idea/OsgiResourceBundle" ).getString(
                                      "settings.import"
                                  )
        );
        m_mainPanel.add( label1, new GridConstraints( 0, 0, 1, 1, GridConstraints.ANCHOR_WEST,
                                                      GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                                                      GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false
        )
        );
        final JScrollPane scrollPane1 = new JScrollPane();
        m_mainPanel.add( scrollPane1, new GridConstraints( 1, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                                                           GridConstraints.FILL_BOTH, GridConstraints
            .SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                           | GridConstraints.SIZEPOLICY_WANT_GROW, null,
                                                                                                                   null,
                                                                                                                   null,
                                                                                                                   0,
                                                                                                                   false
        )
        );
        scrollPane1.setViewportView( m_importList );
    }

    private void $$$loadLabelText$$$( JLabel component, String text )
    {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for( int i = 0; i < text.length(); i++ )
        {
            if( text.charAt( i ) == '&' )
            {
                i++;
                if( i == text.length() )
                {
                    break;
                }
                if( !haveMnemonic && text.charAt( i ) != '&' )
                {
                    haveMnemonic = true;
                    mnemonic = text.charAt( i );
                    mnemonicIndex = result.length();
                }
            }
            result.append( text.charAt( i ) );
        }
        component.setText( result.toString() );
        if( haveMnemonic )
        {
            component.setDisplayedMnemonic( mnemonic );
            component.setDisplayedMnemonicIndex( mnemonicIndex );
        }
    }

    public javax.swing.JComponent $$$getRootComponent$$$()
    {
        return m_mainPanel;
    }
}
