//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.11 at 05:48:47 PM MYT 
//


package org.ops4j.pax.runner.pom;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.ops4j.pax.runner.pom.Build.Extensions;
import org.ops4j.pax.runner.pom.CiManagement.Notifiers;
import org.ops4j.pax.runner.pom.Dependency.Exclusions;
import org.ops4j.pax.runner.pom.MailingList.OtherArchives;
import org.ops4j.pax.runner.pom.Model.Contributors;
import org.ops4j.pax.runner.pom.Model.Developers;
import org.ops4j.pax.runner.pom.Model.Licenses;
import org.ops4j.pax.runner.pom.Model.MailingLists;
import org.ops4j.pax.runner.pom.Model.Profiles;
import org.ops4j.pax.runner.pom.Plugin.Executions;
import org.ops4j.pax.runner.pom.ReportPlugin.ReportSets;
import org.ops4j.pax.runner.pom.Resource.Excludes;
import org.ops4j.pax.runner.pom.Resource.Includes;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ops4j.pax.runner.pom package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Project_QNAME = new QName("http://maven.apache.org/POM/4.0.0", "project");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ops4j.pax.runner.pom
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Exclusions }
     * 
     */
    public Exclusions createDependencyExclusions() {
        return new Exclusions();
    }

    /**
     * Create an instance of {@link ReportSets }
     * 
     */
    public ReportSets createReportPluginReportSets() {
        return new ReportSets();
    }

    /**
     * Create an instance of {@link Executions }
     * 
     */
    public Executions createPluginExecutions() {
        return new Executions();
    }

    /**
     * Create an instance of {@link DistributionManagement }
     * 
     */
    public DistributionManagement createDistributionManagement() {
        return new DistributionManagement();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.ReportPlugin.Configuration }
     * 
     */
    public org.ops4j.pax.runner.pom.ReportPlugin.Configuration createReportPluginConfiguration() {
        return new org.ops4j.pax.runner.pom.ReportPlugin.Configuration();
    }

    /**
     * Create an instance of {@link DeploymentRepository }
     * 
     */
    public DeploymentRepository createDeploymentRepository() {
        return new DeploymentRepository();
    }

    /**
     * Create an instance of {@link Reporting }
     * 
     */
    public Reporting createReporting() {
        return new Reporting();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Contributor.Properties }
     * 
     */
    public org.ops4j.pax.runner.pom.Contributor.Properties createContributorProperties() {
        return new org.ops4j.pax.runner.pom.Contributor.Properties();
    }

    /**
     * Create an instance of {@link Site }
     * 
     */
    public Site createSite() {
        return new Site();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.BuildBase.Resources }
     * 
     */
    public org.ops4j.pax.runner.pom.BuildBase.Resources createBuildBaseResources() {
        return new org.ops4j.pax.runner.pom.BuildBase.Resources();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.ReportSet.Reports }
     * 
     */
    public org.ops4j.pax.runner.pom.ReportSet.Reports createReportSetReports() {
        return new org.ops4j.pax.runner.pom.ReportSet.Reports();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Build.Plugins }
     * 
     */
    public org.ops4j.pax.runner.pom.Build.Plugins createBuildPlugins() {
        return new org.ops4j.pax.runner.pom.Build.Plugins();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Developer.Properties }
     * 
     */
    public org.ops4j.pax.runner.pom.Developer.Properties createDeveloperProperties() {
        return new org.ops4j.pax.runner.pom.Developer.Properties();
    }

    /**
     * Create an instance of {@link Notifier }
     * 
     */
    public Notifier createNotifier() {
        return new Notifier();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.DependencyManagement.Dependencies }
     * 
     */
    public org.ops4j.pax.runner.pom.DependencyManagement.Dependencies createDependencyManagementDependencies() {
        return new org.ops4j.pax.runner.pom.DependencyManagement.Dependencies();
    }

    /**
     * Create an instance of {@link MailingLists }
     * 
     */
    public MailingLists createModelMailingLists() {
        return new MailingLists();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.BuildBase.Plugins }
     * 
     */
    public org.ops4j.pax.runner.pom.BuildBase.Plugins createBuildBasePlugins() {
        return new org.ops4j.pax.runner.pom.BuildBase.Plugins();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Developer.Roles }
     * 
     */
    public org.ops4j.pax.runner.pom.Developer.Roles createDeveloperRoles() {
        return new org.ops4j.pax.runner.pom.Developer.Roles();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Model.Properties }
     * 
     */
    public org.ops4j.pax.runner.pom.Model.Properties createModelProperties() {
        return new org.ops4j.pax.runner.pom.Model.Properties();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Model.Reports }
     * 
     */
    public org.ops4j.pax.runner.pom.Model.Reports createModelReports() {
        return new org.ops4j.pax.runner.pom.Model.Reports();
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Model.Dependencies }
     * 
     */
    public org.ops4j.pax.runner.pom.Model.Dependencies createModelDependencies() {
        return new org.ops4j.pax.runner.pom.Model.Dependencies();
    }

    /**
     * Create an instance of {@link ReportSet }
     * 
     */
    public ReportSet createReportSet() {
        return new ReportSet();
    }

    /**
     * Create an instance of {@link OtherArchives }
     * 
     */
    public OtherArchives createMailingListOtherArchives() {
        return new OtherArchives();
    }

    /**
     * Create an instance of {@link Plugin }
     * 
     */
    public Plugin createPlugin() {
        return new Plugin();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Model.Modules }
     * 
     */
    public org.ops4j.pax.runner.pom.Model.Modules createModelModules() {
        return new org.ops4j.pax.runner.pom.Model.Modules();
    }

    /**
     * Create an instance of {@link CiManagement }
     * 
     */
    public CiManagement createCiManagement() {
        return new CiManagement();
    }

    /**
     * Create an instance of {@link License }
     * 
     */
    public License createLicense() {
        return new License();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.BuildBase.TestResources }
     * 
     */
    public org.ops4j.pax.runner.pom.BuildBase.TestResources createBuildBaseTestResources() {
        return new org.ops4j.pax.runner.pom.BuildBase.TestResources();
    }

    /**
     * Create an instance of {@link Profiles }
     * 
     */
    public Profiles createModelProfiles() {
        return new Profiles();
    }

    /**
     * Create an instance of {@link Build }
     * 
     */
    public Build createBuild() {
        return new Build();
    }

    /**
     * Create an instance of {@link Licenses }
     * 
     */
    public Licenses createModelLicenses() {
        return new Licenses();
    }

    /**
     * Create an instance of {@link Notifiers }
     * 
     */
    public Notifiers createCiManagementNotifiers() {
        return new Notifiers();
    }

    /**
     * Create an instance of {@link Prerequisites }
     * 
     */
    public Prerequisites createPrerequisites() {
        return new Prerequisites();
    }

    /**
     * Create an instance of {@link PluginExecution }
     * 
     */
    public PluginExecution createPluginExecution() {
        return new PluginExecution();
    }

    /**
     * Create an instance of {@link Relocation }
     * 
     */
    public Relocation createRelocation() {
        return new Relocation();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Profile.Properties }
     * 
     */
    public org.ops4j.pax.runner.pom.Profile.Properties createProfileProperties() {
        return new org.ops4j.pax.runner.pom.Profile.Properties();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Model.PluginRepositories }
     * 
     */
    public org.ops4j.pax.runner.pom.Model.PluginRepositories createModelPluginRepositories() {
        return new org.ops4j.pax.runner.pom.Model.PluginRepositories();
    }

    /**
     * Create an instance of {@link Scm }
     * 
     */
    public Scm createScm() {
        return new Scm();
    }

    /**
     * Create an instance of {@link BuildBase }
     * 
     */
    public BuildBase createBuildBase() {
        return new BuildBase();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Build.Resources }
     * 
     */
    public org.ops4j.pax.runner.pom.Build.Resources createBuildResources() {
        return new org.ops4j.pax.runner.pom.Build.Resources();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.PluginExecution.Configuration }
     * 
     */
    public org.ops4j.pax.runner.pom.PluginExecution.Configuration createPluginExecutionConfiguration() {
        return new org.ops4j.pax.runner.pom.PluginExecution.Configuration();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link ReportPlugin }
     * 
     */
    public ReportPlugin createReportPlugin() {
        return new ReportPlugin();
    }

    /**
     * Create an instance of {@link Repository }
     * 
     */
    public Repository createRepository() {
        return new Repository();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Profile.PluginRepositories }
     * 
     */
    public org.ops4j.pax.runner.pom.Profile.PluginRepositories createProfilePluginRepositories() {
        return new org.ops4j.pax.runner.pom.Profile.PluginRepositories();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Reporting.Plugins }
     * 
     */
    public org.ops4j.pax.runner.pom.Reporting.Plugins createReportingPlugins() {
        return new org.ops4j.pax.runner.pom.Reporting.Plugins();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Profile.Reports }
     * 
     */
    public org.ops4j.pax.runner.pom.Profile.Reports createProfileReports() {
        return new org.ops4j.pax.runner.pom.Profile.Reports();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Build.TestResources }
     * 
     */
    public org.ops4j.pax.runner.pom.Build.TestResources createBuildTestResources() {
        return new org.ops4j.pax.runner.pom.Build.TestResources();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.PluginManagement.Plugins }
     * 
     */
    public org.ops4j.pax.runner.pom.PluginManagement.Plugins createPluginManagementPlugins() {
        return new org.ops4j.pax.runner.pom.PluginManagement.Plugins();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Plugin.Configuration }
     * 
     */
    public org.ops4j.pax.runner.pom.Plugin.Configuration createPluginConfiguration() {
        return new org.ops4j.pax.runner.pom.Plugin.Configuration();
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     */
    public Extensions createBuildExtensions() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link DependencyManagement }
     * 
     */
    public DependencyManagement createDependencyManagement() {
        return new DependencyManagement();
    }

    /**
     * Create an instance of {@link Exclusion }
     * 
     */
    public Exclusion createExclusion() {
        return new Exclusion();
    }

    /**
     * Create an instance of {@link Includes }
     * 
     */
    public Includes createResourceIncludes() {
        return new Includes();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Notifier.Configuration }
     * 
     */
    public org.ops4j.pax.runner.pom.Notifier.Configuration createNotifierConfiguration() {
        return new org.ops4j.pax.runner.pom.Notifier.Configuration();
    }

    /**
     * Create an instance of {@link ActivationFile }
     * 
     */
    public ActivationFile createActivationFile() {
        return new ActivationFile();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Plugin.Dependencies }
     * 
     */
    public org.ops4j.pax.runner.pom.Plugin.Dependencies createPluginDependencies() {
        return new org.ops4j.pax.runner.pom.Plugin.Dependencies();
    }

    /**
     * Create an instance of {@link PluginManagement }
     * 
     */
    public PluginManagement createPluginManagement() {
        return new PluginManagement();
    }

    /**
     * Create an instance of {@link Dependency }
     * 
     */
    public Dependency createDependency() {
        return new Dependency();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Profile.Repositories }
     * 
     */
    public org.ops4j.pax.runner.pom.Profile.Repositories createProfileRepositories() {
        return new org.ops4j.pax.runner.pom.Profile.Repositories();
    }

    /**
     * Create an instance of {@link MailingList }
     * 
     */
    public MailingList createMailingList() {
        return new MailingList();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.PluginExecution.Goals }
     * 
     */
    public org.ops4j.pax.runner.pom.PluginExecution.Goals createPluginExecutionGoals() {
        return new org.ops4j.pax.runner.pom.PluginExecution.Goals();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Profile.Dependencies }
     * 
     */
    public org.ops4j.pax.runner.pom.Profile.Dependencies createProfileDependencies() {
        return new org.ops4j.pax.runner.pom.Profile.Dependencies();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.BuildBase.Filters }
     * 
     */
    public org.ops4j.pax.runner.pom.BuildBase.Filters createBuildBaseFilters() {
        return new org.ops4j.pax.runner.pom.BuildBase.Filters();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Model.Repositories }
     * 
     */
    public org.ops4j.pax.runner.pom.Model.Repositories createModelRepositories() {
        return new org.ops4j.pax.runner.pom.Model.Repositories();
    }

    /**
     * Create an instance of {@link ActivationOS }
     * 
     */
    public ActivationOS createActivationOS() {
        return new ActivationOS();
    }

    /**
     * Create an instance of {@link Activation }
     * 
     */
    public Activation createActivation() {
        return new Activation();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Build.Filters }
     * 
     */
    public org.ops4j.pax.runner.pom.Build.Filters createBuildFilters() {
        return new org.ops4j.pax.runner.pom.Build.Filters();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Profile.Modules }
     * 
     */
    public org.ops4j.pax.runner.pom.Profile.Modules createProfileModules() {
        return new org.ops4j.pax.runner.pom.Profile.Modules();
    }

    /**
     * Create an instance of {@link Contributors }
     * 
     */
    public Contributors createModelContributors() {
        return new Contributors();
    }

    /**
     * Create an instance of {@link Developers }
     * 
     */
    public Developers createModelDevelopers() {
        return new Developers();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Plugin.Goals }
     * 
     */
    public org.ops4j.pax.runner.pom.Plugin.Goals createPluginGoals() {
        return new org.ops4j.pax.runner.pom.Plugin.Goals();
    }

    /**
     * Create an instance of {@link Excludes }
     * 
     */
    public Excludes createResourceExcludes() {
        return new Excludes();
    }

    /**
     * Create an instance of {@link RepositoryPolicy }
     * 
     */
    public RepositoryPolicy createRepositoryPolicy() {
        return new RepositoryPolicy();
    }

    /**
     * Create an instance of {@link Developer }
     * 
     */
    public Developer createDeveloper() {
        return new Developer();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.ReportSet.Configuration }
     * 
     */
    public org.ops4j.pax.runner.pom.ReportSet.Configuration createReportSetConfiguration() {
        return new org.ops4j.pax.runner.pom.ReportSet.Configuration();
    }

    /**
     * Create an instance of {@link ActivationProperty }
     * 
     */
    public ActivationProperty createActivationProperty() {
        return new ActivationProperty();
    }

    /**
     * Create an instance of {@link IssueManagement }
     * 
     */
    public IssueManagement createIssueManagement() {
        return new IssueManagement();
    }

    /**
     * Create an instance of {@link Contributor }
     * 
     */
    public Contributor createContributor() {
        return new Contributor();
    }

    /**
     * Create an instance of {@link Parent }
     * 
     */
    public Parent createParent() {
        return new Parent();
    }

    /**
     * Create an instance of {@link org.ops4j.pax.runner.pom.Contributor.Roles }
     * 
     */
    public org.ops4j.pax.runner.pom.Contributor.Roles createContributorRoles() {
        return new org.ops4j.pax.runner.pom.Contributor.Roles();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Model }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://maven.apache.org/POM/4.0.0", name = "project")
    public JAXBElement<Model> createProject(Model value) {
        return new JAXBElement<Model>(_Project_QNAME, Model.class, null, value);
    }

}
