//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.09.11 at 05:48:47 PM MYT
//

@javax.xml.bind.annotation.XmlSchema(
    namespace = "http://maven.apache.org/POM/4.0.0" ) package org.ops4j.pax.runner.pom;
