//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.09.11 at 05:48:47 PM MYT
//

package org.ops4j.pax.pomparser.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

/**
 * 4.0.0
 *
 * <p>Java class for Plugin complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Plugin">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="extensions" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="executions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="execution" type="{http://maven.apache.org/POM/4.0.0}PluginExecution" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dependencies" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dependency" type="{http://maven.apache.org/POM/4.0.0}Dependency" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="goals" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="inherited" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="configuration" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "Plugin", propOrder = {

    } )
public class Plugin
{

    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", defaultValue = "org.apache.maven.plugins" )
    protected String groupId;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected String artifactId;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected String version;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", defaultValue = "false" )
    protected Boolean extensions;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Executions executions;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Dependencies dependencies;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Goals goals;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected String inherited;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Configuration configuration;

    /**
     * Gets the value of the groupId property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getGroupId()
    {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGroupId( String value )
    {
        this.groupId = value;
    }

    /**
     * Gets the value of the artifactId property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getArtifactId()
    {
        return artifactId;
    }

    /**
     * Sets the value of the artifactId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setArtifactId( String value )
    {
        this.artifactId = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getVersion()
    {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersion( String value )
    {
        this.version = value;
    }

    /**
     * Gets the value of the extensions property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean isExtensions()
    {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setExtensions( Boolean value )
    {
        this.extensions = value;
    }

    /**
     * Gets the value of the executions property.
     *
     * @return possible object is
     *         {@link Executions }
     */
    public Executions getExecutions()
    {
        return executions;
    }

    /**
     * Sets the value of the executions property.
     *
     * @param value allowed object is
     *              {@link Executions }
     */
    public void setExecutions( Executions value )
    {
        this.executions = value;
    }

    /**
     * Gets the value of the dependencies property.
     *
     * @return possible object is
     *         {@link Dependencies }
     */
    public Dependencies getDependencies()
    {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     *
     * @param value allowed object is
     *              {@link Dependencies }
     */
    public void setDependencies( Dependencies value )
    {
        this.dependencies = value;
    }

    /**
     * Gets the value of the goals property.
     *
     * @return possible object is
     *         {@link Goals }
     */
    public Goals getGoals()
    {
        return goals;
    }

    /**
     * Sets the value of the goals property.
     *
     * @param value allowed object is
     *              {@link Goals }
     */
    public void setGoals( Goals value )
    {
        this.goals = value;
    }

    /**
     * Gets the value of the inherited property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getInherited()
    {
        return inherited;
    }

    /**
     * Sets the value of the inherited property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInherited( String value )
    {
        this.inherited = value;
    }

    /**
     * Gets the value of the configuration property.
     *
     * @return possible object is
     *         {@link Configuration }
     */
    public Configuration getConfiguration()
    {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     *
     * @param value allowed object is
     *              {@link Configuration }
     */
    public void setConfiguration( Configuration value )
    {
        this.configuration = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "any"
        } )
    public static class Configuration
    {

        @XmlAnyElement
        protected List<Element> any;

        /**
         * Gets the value of the any property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         */
        public List<Element> getAny()
        {
            if( any == null )
            {
                any = new ArrayList<Element>();
            }
            return this.any;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dependency" type="{http://maven.apache.org/POM/4.0.0}Dependency" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "dependency"
        } )
    public static class Dependencies
    {

        @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", required = true )
        protected List<Dependency> dependency;

        /**
         * Gets the value of the dependency property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dependency property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDependency().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dependency }
         */
        public List<Dependency> getDependency()
        {
            if( dependency == null )
            {
                dependency = new ArrayList<Dependency>();
            }
            return this.dependency;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="execution" type="{http://maven.apache.org/POM/4.0.0}PluginExecution" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "execution"
        } )
    public static class Executions
    {

        @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", required = true )
        protected List<PluginExecution> execution;

        /**
         * Gets the value of the execution property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the execution property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExecution().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PluginExecution }
         */
        public List<PluginExecution> getExecution()
        {
            if( execution == null )
            {
                execution = new ArrayList<PluginExecution>();
            }
            return this.execution;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "any"
        } )
    public static class Goals
    {

        @XmlAnyElement
        protected List<Element> any;

        /**
         * Gets the value of the any property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         */
        public List<Element> getAny()
        {
            if( any == null )
            {
                any = new ArrayList<Element>();
            }
            return this.any;
        }

    }

}
