//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.09.11 at 05:48:47 PM MYT
//

package org.ops4j.pax.pomparser.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

/**
 * Modifications to the build process which is keyed on some
 * sort of environmental parameter.
 *
 *
 * <p>Java class for Profile complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Profile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="activation" type="{http://maven.apache.org/POM/4.0.0}Activation" minOccurs="0"/>
 *         &lt;element name="build" type="{http://maven.apache.org/POM/4.0.0}BuildBase" minOccurs="0"/>
 *         &lt;element name="modules" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="module" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="repositories" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="repository" type="{http://maven.apache.org/POM/4.0.0}Repository" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pluginRepositories" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pluginRepository" type="{http://maven.apache.org/POM/4.0.0}Repository" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dependencies" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dependency" type="{http://maven.apache.org/POM/4.0.0}Dependency" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reports" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reporting" type="{http://maven.apache.org/POM/4.0.0}Reporting" minOccurs="0"/>
 *         &lt;element name="dependencyManagement" type="{http://maven.apache.org/POM/4.0.0}DependencyManagement" minOccurs="0"/>
 *         &lt;element name="distributionManagement" type="{http://maven.apache.org/POM/4.0.0}DistributionManagement" minOccurs="0"/>
 *         &lt;element name="properties" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "Profile", propOrder = {

    } )
public class Profile
{

    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected String id;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Activation activation;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected BuildBase build;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Modules modules;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Repositories repositories;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected PluginRepositories pluginRepositories;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Dependencies dependencies;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Reports reports;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Reporting reporting;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected DependencyManagement dependencyManagement;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected DistributionManagement distributionManagement;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Properties properties;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getId()
    {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId( String value )
    {
        this.id = value;
    }

    /**
     * Gets the value of the activation property.
     *
     * @return possible object is
     *         {@link Activation }
     */
    public Activation getActivation()
    {
        return activation;
    }

    /**
     * Sets the value of the activation property.
     *
     * @param value allowed object is
     *              {@link Activation }
     */
    public void setActivation( Activation value )
    {
        this.activation = value;
    }

    /**
     * Gets the value of the build property.
     *
     * @return possible object is
     *         {@link BuildBase }
     */
    public BuildBase getBuild()
    {
        return build;
    }

    /**
     * Sets the value of the build property.
     *
     * @param value allowed object is
     *              {@link BuildBase }
     */
    public void setBuild( BuildBase value )
    {
        this.build = value;
    }

    /**
     * Gets the value of the modules property.
     *
     * @return possible object is
     *         {@link Modules }
     */
    public Modules getModules()
    {
        return modules;
    }

    /**
     * Sets the value of the modules property.
     *
     * @param value allowed object is
     *              {@link Modules }
     */
    public void setModules( Modules value )
    {
        this.modules = value;
    }

    /**
     * Gets the value of the repositories property.
     *
     * @return possible object is
     *         {@link Repositories }
     */
    public Repositories getRepositories()
    {
        return repositories;
    }

    /**
     * Sets the value of the repositories property.
     *
     * @param value allowed object is
     *              {@link Repositories }
     */
    public void setRepositories( Repositories value )
    {
        this.repositories = value;
    }

    /**
     * Gets the value of the pluginRepositories property.
     *
     * @return possible object is
     *         {@link PluginRepositories }
     */
    public PluginRepositories getPluginRepositories()
    {
        return pluginRepositories;
    }

    /**
     * Sets the value of the pluginRepositories property.
     *
     * @param value allowed object is
     *              {@link PluginRepositories }
     */
    public void setPluginRepositories( PluginRepositories value )
    {
        this.pluginRepositories = value;
    }

    /**
     * Gets the value of the dependencies property.
     *
     * @return possible object is
     *         {@link Dependencies }
     */
    public Dependencies getDependencies()
    {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     *
     * @param value allowed object is
     *              {@link Dependencies }
     */
    public void setDependencies( Dependencies value )
    {
        this.dependencies = value;
    }

    /**
     * Gets the value of the reports property.
     *
     * @return possible object is
     *         {@link Reports }
     */
    public Reports getReports()
    {
        return reports;
    }

    /**
     * Sets the value of the reports property.
     *
     * @param value allowed object is
     *              {@link Reports }
     */
    public void setReports( Reports value )
    {
        this.reports = value;
    }

    /**
     * Gets the value of the reporting property.
     *
     * @return possible object is
     *         {@link Reporting }
     */
    public Reporting getReporting()
    {
        return reporting;
    }

    /**
     * Sets the value of the reporting property.
     *
     * @param value allowed object is
     *              {@link Reporting }
     */
    public void setReporting( Reporting value )
    {
        this.reporting = value;
    }

    /**
     * Gets the value of the dependencyManagement property.
     *
     * @return possible object is
     *         {@link DependencyManagement }
     */
    public DependencyManagement getDependencyManagement()
    {
        return dependencyManagement;
    }

    /**
     * Sets the value of the dependencyManagement property.
     *
     * @param value allowed object is
     *              {@link DependencyManagement }
     */
    public void setDependencyManagement( DependencyManagement value )
    {
        this.dependencyManagement = value;
    }

    /**
     * Gets the value of the distributionManagement property.
     *
     * @return possible object is
     *         {@link DistributionManagement }
     */
    public DistributionManagement getDistributionManagement()
    {
        return distributionManagement;
    }

    /**
     * Sets the value of the distributionManagement property.
     *
     * @param value allowed object is
     *              {@link DistributionManagement }
     */
    public void setDistributionManagement( DistributionManagement value )
    {
        this.distributionManagement = value;
    }

    /**
     * Gets the value of the properties property.
     *
     * @return possible object is
     *         {@link Properties }
     */
    public Properties getProperties()
    {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     *
     * @param value allowed object is
     *              {@link Properties }
     */
    public void setProperties( Properties value )
    {
        this.properties = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dependency" type="{http://maven.apache.org/POM/4.0.0}Dependency" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "dependency"
        } )
    public static class Dependencies
    {

        @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", required = true )
        protected List<Dependency> dependency;

        /**
         * Gets the value of the dependency property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dependency property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDependency().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dependency }
         */
        public List<Dependency> getDependency()
        {
            if( dependency == null )
            {
                dependency = new ArrayList<Dependency>();
            }
            return this.dependency;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="module" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "module"
        } )
    public static class Modules
    {

        @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", required = true )
        protected List<String> module;

        /**
         * Gets the value of the module property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the module property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getModule().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         */
        public List<String> getModule()
        {
            if( module == null )
            {
                module = new ArrayList<String>();
            }
            return this.module;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pluginRepository" type="{http://maven.apache.org/POM/4.0.0}Repository" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "pluginRepository"
        } )
    public static class PluginRepositories
    {

        @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", required = true )
        protected List<Repository> pluginRepository;

        /**
         * Gets the value of the pluginRepository property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pluginRepository property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPluginRepository().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Repository }
         */
        public List<Repository> getPluginRepository()
        {
            if( pluginRepository == null )
            {
                pluginRepository = new ArrayList<Repository>();
            }
            return this.pluginRepository;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "any"
        } )
    public static class Properties
    {

        @XmlAnyElement
        protected List<Element> any;

        /**
         * Gets the value of the any property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         */
        public List<Element> getAny()
        {
            if( any == null )
            {
                any = new ArrayList<Element>();
            }
            return this.any;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "any"
        } )
    public static class Reports
    {

        @XmlAnyElement
        protected List<Element> any;

        /**
         * Gets the value of the any property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         */
        public List<Element> getAny()
        {
            if( any == null )
            {
                any = new ArrayList<Element>();
            }
            return this.any;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="repository" type="{http://maven.apache.org/POM/4.0.0}Repository" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "repository"
        } )
    public static class Repositories
    {

        @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", required = true )
        protected List<Repository> repository;

        /**
         * Gets the value of the repository property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the repository property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRepository().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Repository }
         */
        public List<Repository> getRepository()
        {
            if( repository == null )
            {
                repository = new ArrayList<Repository>();
            }
            return this.repository;
        }

    }

}
