//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.09.11 at 05:48:47 PM MYT
//

package org.ops4j.pax.pomparser.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;

/**
 * Represents a set of reports and configuration to be used to generate them.
 *
 * <p>Java class for ReportSet complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ReportSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="configuration" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="inherited" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reports" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "ReportSet", propOrder = {

    } )
public class ReportSet
{

    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected String id;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Configuration configuration;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected String inherited;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Reports reports;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getId()
    {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId( String value )
    {
        this.id = value;
    }

    /**
     * Gets the value of the configuration property.
     *
     * @return possible object is
     *         {@link Configuration }
     */
    public Configuration getConfiguration()
    {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     *
     * @param value allowed object is
     *              {@link Configuration }
     */
    public void setConfiguration( Configuration value )
    {
        this.configuration = value;
    }

    /**
     * Gets the value of the inherited property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getInherited()
    {
        return inherited;
    }

    /**
     * Sets the value of the inherited property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInherited( String value )
    {
        this.inherited = value;
    }

    /**
     * Gets the value of the reports property.
     *
     * @return possible object is
     *         {@link Reports }
     */
    public Reports getReports()
    {
        return reports;
    }

    /**
     * Sets the value of the reports property.
     *
     * @param value allowed object is
     *              {@link Reports }
     */
    public void setReports( Reports value )
    {
        this.reports = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "any"
        } )
    public static class Configuration
    {

        @XmlAnyElement
        protected List<Element> any;

        /**
         * Gets the value of the any property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         */
        public List<Element> getAny()
        {
            if( any == null )
            {
                any = new ArrayList<Element>();
            }
            return this.any;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="report" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "report"
        } )
    public static class Reports
    {

        @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", required = true )
        protected List<String> report;

        /**
         * Gets the value of the report property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the report property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReport().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         */
        public List<String> getReport()
        {
            if( report == null )
            {
                report = new ArrayList<String>();
            }
            return this.report;
        }

    }

}
