//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2006.09.11 at 05:48:47 PM MYT
//

package org.ops4j.pax.pomparser.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This element describes all of the resources associated with a project or
 * unit tests. Each resource is described by a resource element, which is
 * then described by additional elements (described
 * <a href="#resource">below</a>). These resources are used to complete the
 * jar file or to run unit test.
 *
 *
 * <p>Java class for Resource complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Resource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="targetPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="filtering" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="directory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="includes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="include" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="excludes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="exclude" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "Resource", propOrder = {

    } )
public class Resource
{

    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected String targetPath;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", defaultValue = "false" )
    protected Boolean filtering;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected String directory;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Includes includes;
    @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0" )
    protected Excludes excludes;

    /**
     * Gets the value of the targetPath property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTargetPath()
    {
        return targetPath;
    }

    /**
     * Sets the value of the targetPath property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTargetPath( String value )
    {
        this.targetPath = value;
    }

    /**
     * Gets the value of the filtering property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean isFiltering()
    {
        return filtering;
    }

    /**
     * Sets the value of the filtering property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setFiltering( Boolean value )
    {
        this.filtering = value;
    }

    /**
     * Gets the value of the directory property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDirectory()
    {
        return directory;
    }

    /**
     * Sets the value of the directory property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDirectory( String value )
    {
        this.directory = value;
    }

    /**
     * Gets the value of the includes property.
     *
     * @return possible object is
     *         {@link Includes }
     */
    public Includes getIncludes()
    {
        return includes;
    }

    /**
     * Sets the value of the includes property.
     *
     * @param value allowed object is
     *              {@link Includes }
     */
    public void setIncludes( Includes value )
    {
        this.includes = value;
    }

    /**
     * Gets the value of the excludes property.
     *
     * @return possible object is
     *         {@link Excludes }
     */
    public Excludes getExcludes()
    {
        return excludes;
    }

    /**
     * Sets the value of the excludes property.
     *
     * @param value allowed object is
     *              {@link Excludes }
     */
    public void setExcludes( Excludes value )
    {
        this.excludes = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="exclude" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "exclude"
        } )
    public static class Excludes
    {

        @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", required = true )
        protected List<String> exclude;

        /**
         * Gets the value of the exclude property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the exclude property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExclude().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         */
        public List<String> getExclude()
        {
            if( exclude == null )
            {
                exclude = new ArrayList<String>();
            }
            return this.exclude;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="include" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType( XmlAccessType.FIELD )
    @XmlType( name = "", propOrder = {
        "include"
        } )
    public static class Includes
    {

        @XmlElement( namespace = "http://maven.apache.org/POM/4.0.0", required = true )
        protected List<String> include;

        /**
         * Gets the value of the include property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the include property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInclude().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         */
        public List<String> getInclude()
        {
            if( include == null )
            {
                include = new ArrayList<String>();
            }
            return this.include;
        }

    }

}
